BACKPORT: seccomp: add filter_count field for KernelSU • KernelSU requires struct seccomp to have atomic_t filter_count , but this field is missing on NON-GKI kernels.
Adding the field fixes build errors such as:

 error: no member named 'filter_count' in 'struct seccomp'
 Reference: https://github.com/tiann/KernelSU/pull/2708

Actual Commit: https://github.com/GrapheneOS-Archive/kernel_common-5.10/commit/c818c03

Signed-off-by: Kees Cook <keescook@chromium.org>